apiVersion: apps/v1
kind: Deployment
metadata:
  name: springboot-crud-deployment
spec:
  selector:
    matchLabels:
      app: spring-k8s-mysql
  replicas: 3
  template:
    metadata:
      labels:
        app: spring-k8s-mysql
    spec:
      containers:
        - name: crud-k8s
          image: crud-k8s:2.0
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          env: # Setting Environmental Variables
            - name: DB_HOST   # Setting Database host address from configMap
              valueFrom:
                configMapKeyRef:
                  name: db-configuration
                  key: host

            - name: DB_NAME  # Setting Database name from configMap
              valueFrom:
                configMapKeyRef:
                  name: db-configuration
                  key: dbName

            - name: DB_USERNAME  # Setting Database username from Secret
              valueFrom:
                secretKeyRef:
                  name: mysql-secrets
                  key: username

            - name: DB_PASSWORD # Setting Database password from Secret
              valueFrom:
                secretKeyRef:
                  name: mysql-secrets
                  key: password

---
# Service
apiVersion: v1
kind: Service
metadata:
  name: spring-crud-svc
spec:
  selector:
    app: spring-k8s-mysql
  ports:
    - protocol: "TCP"
      port: 8080 # The port that the service is running on in the cluster
      targetPort: 8080 # The port exposed by the service
  type: NodePort # type of the service.

